"""users table

Revision ID: 28af4e0990cf
Revises: 
Create Date: 2025-05-19 07:08:50.858022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28af4e0990cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_default'), ['default'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planta', sa.String(length=64), nullable=False),
    sa.Column('descricao', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plant_planta'), ['planta'], unique=False)
        batch_op.create_index(batch_op.f('ix_plant_user_id'), ['user_id'], unique=False)

    op.create_table('troca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=64), nullable=False),
    sa.Column('local', sa.String(length=128), nullable=False),
    sa.Column('descricao', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('troca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_troca_titulo'), ['titulo'], unique=False)
        batch_op.create_index(batch_op.f('ix_troca_user_id'), ['user_id'], unique=False)

    op.create_table('tarefa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.String(length=128), nullable=True),
    sa.Column('data_programada', sa.DateTime(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tarefa_plant_id'), ['plant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tarefa_titulo'), ['titulo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tarefa_titulo'))
        batch_op.drop_index(batch_op.f('ix_tarefa_plant_id'))

    op.drop_table('tarefa')
    with op.batch_alter_table('troca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_troca_user_id'))
        batch_op.drop_index(batch_op.f('ix_troca_titulo'))

    op.drop_table('troca')
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plant_user_id'))
        batch_op.drop_index(batch_op.f('ix_plant_planta'))

    op.drop_table('plant')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_default'))

    op.drop_table('roles')
    # ### end Alembic commands ###
